name = "drss"
author = "intergrav"
version = "1.0.0+1.20.1.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e8139493320da5f0ce42e80f98bbb315afa39247634765e344f883da767f85e"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
